### ISSUE TITLE
There is no dictory path '/DeepFLASH/data/Rnet/' and '/DeepFLASH/data/Inet'

### ISSUE THREAD

**Issue by ljl913479576** [jw4hv/deepflash#5]
When I use ''preprocessmhd.m'' to create data,  only generated one ''mhd file'', and I can't find  Vopt's real part and image part

**Comment by jw4hv** [comment]
The optimal velocity are generated from a fast image registration algorithm: https://bitbucket.org/FlashC/flashc/src/master/ .
You then put the generated ".mhd" files (source, target, and velocity fields) under the fold of preprocessing.
