### ISSUE TITLE
About the bandlimited initial velocity fields

### ISSUE THREAD

**Issue by Joker00007** [jw4hv/deepflash#6]
Hello,If the bandlimited initial velocity fields is Deformation field after registration?
and I always cannot configure pyca and flashC' environment,if there are others way to get the bandlimited initial velocity fields?

**Comment by jw4hv** [comment]
The bandlimited initial velocity fields can be generated by applying FFT on spatial velocity fields, which are optimal image registration solutions. You can run the preprocessing code in "/deepflash/preprocessmhd.m" to have those low-dimensional band limited velocity fields. 

Our method should be able to generalized to other deformable image registration methods. However, if you want to use FLASHC, there is another way to produce registration solution without complying PyCA: https://www.notion.so/Using-FLASHC-Docker-Image-042206cc67ce483d8f86371dc9f6fc75

Let me know if this is helpful or further questions.
