### ISSUE TITLE
velocity2fourier3D

### ISSUE THREAD

**Issue by xi-jia** [jw4hv/deepflash#8]
Hi,

I am really confused why the velocity2fourier3D is much different from image2fourier3D.
Shouldn't it be simply doing Fourier transform on each axis and then concatenating them together?

Something like:
```
fourier= fftn(x(1,m,n,p);
vx=fftshift(fourier);
fourier= fftn(x(2,m,n,p);
vy=fftshift(fourier);
fourier= fftn(x(3,m,n,p);
vz=fftshift(fourier);
return concat(vx, vy,vz)
```

Could you please share with me what's the insight of doing fft2 rather than fftn on the velocity field?

**Comment by jw4hv** [comment]
Hi, 

You are right. fft2 is a toy example for the provided 2d case. You shall check the python jupyter notebook for entire preprocessing. fftn is applied for both 2d and 3d case!
